// vuestyled-platziintroframeworks_b33c3e60-f89f-4eb6-a114-741c1cd6f033/src/App.vue
<template>
  <custom-title text="Películas"></custom-title>
  <custom-form></custom-form>
</template>

<script>
import Title from "./components/Title.vue";
import Form from "./components/Form.vue";

export default {
  name: "App",
  components: {
    "custom-title": Title,
    "custom-form": Form,
  },
  data() {
    return {
      movies: [
        {
          name: "Avengers",
          available: 3,
          quantity: 0,
        },
        {
          name: "Terminator",
          available: 5,
          quantity: 0,
        },
      ],
    };
  },
  methods() {
    return {
      updateMovie(newMovie) {
        const movieIndex = this.movies.findIndex(
          (movie) => movie.name === newMovie.name
        );

        this.movies[movieIndex] = newMovie;
      },
    };
  },
};
</script>

<style lang="scss">
@import "./styles/variables.scss";

* {
  box-sizing: border-box;
}

body {
  background: $bg;
  color: $color;
  margin: 0;
  line-height: 1.5;
}
</style>

// angularcssmovies_c3a8e889-1676-480d-bda0-96161a0c9f97/src/app/app.component.ts
import { Component } from '@angular/core';

type Movie = {
  name: String;
  available: Number;
  quantity: Number;
};

type Movies = Array<Movie>;

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
})
export class AppComponent {
  title: String = 'Películas';
  movies: Movies = [
    {
      name: 'Avengers',
      available: 3,
      quantity: 0,
    },
    {
      name: 'Terminator',
      available: 5,
      quantity: 0,
    },
  ];

  addMovieQuantity(movieName) {
    const movieIndex = this.movies.findIndex(
      (movie) => movie.name === movieName,
    );

    this.movies[movieIndex].quantity += 1;
  }

  removeMovieQuantity(movieName) {
    const movieIndex = this.movies.findIndex(
      (movie) => movie.name === movieName,
    );

    this.movies[movieIndex].quantity -= 1;
  }
}

<h2>{{ title }}</h2>

<form *ngFor="let movie of movies">
  <h3>{{ movie.name }}</h3>

  <button
    type="button"
    (click)="removeMovieQuantity(movie.name)"
    [disabled]="movie.quantity <= 0"
  >
    -
  </button>
  {{ movie.quantity }}
  <button
    type="button"
    (click)="addMovieQuantity(movie.name)"
    [disabled]="movie.quantity >= movie.available"
  >
    +
  </button>
</form>
